inherit_from: .rubocop_todo.yml

require: rubocop-rails
require: rubocop-rspec

Metrics/BlockLength:
  Enabled: true
  Exclude: 
    - spec/**/*

Metrics/LineLength:
  Max: 120

MethodLength:
  Max: 20
  Exclude:
    - db/migrate/*

BlockLength:
  Max: 40
