require:
  - rubocop-rails
  - rubocop-rspec

Metrics/BlockLength:
  Enabled: true
  Exclude: 
    - spec/**/*

Layout:
  Metrics/LineLength:
    Max: 120

  MethodLength:
    Max: 20
    Exclude:
      - db/migrate/*

  BlockLength:
    Max: 40

RSpec/ContextWording:
 Prefixes:
   - when
   - with
   - without
   - if
   - unless
   - for
